repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
        args:
          - '--assume-in-merge'
      - id: check-added-large-files
        args:
          - '--maxkb=10240'
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        exclude: (app.py|pages)
        additional_dependencies:
          - flake8-bandit
          - flake8-bugbear
          - flake8-docstrings
          - flake8-import-order
          - darglint
          - mypy
          - pycodestyle
          - pydocstyle
        args:
          - '--config'
          - .flake8
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        types_or:
          - python
          - pyi
          - jupyter
        args:
          - '--fix'
      - id: ruff-format
        types_or:
          - python
          - pyi
          - jupyter
Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES