name: black

on: [push]

jobs:
    black:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: black
              uses: psf/black@stable
              with:
                  args: --check .