name: black-action

on: [push, pull_request]

jobs:
  linter_name:
    name: runner / black formatter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - uses: datadog/action-py-black-formatter@v2.1
        with:
          check_mode: "true"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt